server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: msc-clientes
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://srv-test-evaluacion.mysql.database.azure.com:3306/msc_clientes?sslMode=REQUIRED&serverTimezone=UTC}
    username: ${DB_USERNAME:rootmysql}
    password: ${DB_PASSWORD:Ecuador2025$}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
      expiration: 86400000 # 24 hours

logging:
  level:
    com.microservice: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# OpenTelemetry
otel:
  service:
    name: msc-clientes
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
  traces:
    exporter: ${OTEL_TRACES_EXPORTER:logging}
  metrics:
    exporter: ${OTEL_METRICS_EXPORTER:logging}
