name: Build and Deploy to Azure

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (ignorar fallos de test)
        run: mvn clean package -DskipTests || mvn clean package -Dmaven.test.failure.ignore=true

      - name: Zip artifact
        run: zip -j app.zip target/msc-clientes-0.0.1-SNAPSHOT.jar

      - name: Deploy to Azure App Service using Zip Deploy
        run: |
          curl -X POST \
            -u "$AZURE_USER:$AZURE_PASSWORD" \
            --data-binary "@app.zip" \
            "https://test-evaluacion-gvh4a6gde7f8hbbj.scm.eastus2-01.azurewebsites.net/api/zipdeploy"
        env:
          AZURE_USER: ${{ secrets.AZURE_USER }}
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}